name: Build GPU IPC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        os: [ubuntu-20.04]
        sub_packages: ["cuda-nvcc", "cuda-libraries-dev", "cuda-libraries"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.18
        if: ${{ !startsWith(matrix.os, 'macos') }}
        with:
          cuda: '12.5.1'
          method: 'network'
          sub-packages: ${{ matrix.sub_packages }}
          non-cuda-sub-packages: '[]'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libeigen3-dev libglew-dev freeglut3-dev libx11-dev

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCUDA_ARCHITECTURES="86"

      - name: Build with CMake
        run: |
          cd build
          make -j$(nproc)

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
