name: Build GPU IPC
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.18
        if: ${{ !startsWith(matrix.os, 'macos') }}
        with:
          cuda: '11.8.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'
          non-cuda-sub-packages: '["libcublas", "libcusparse", "libcusolver", "libcublas-dev-11-8", "libcusparse-dev-11-8", "libcusolver-dev-11-8"]'

      - name: Remove Duplicate CUDA Repository Entries
        run: |
          sudo rm /etc/apt/sources.list.d/cuda-ubuntu2004-x86_64.list
          sudo apt-get update

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.26.0"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgGitCommitId: 055721089e8037d4d617250814d11f881e557549

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libeigen3-dev libglew-dev freeglut3-dev libx11-dev

      - name: Install ccache
        run: |
          sudo apt-get install -y ccache
          echo 'export PATH="/usr/lib/ccache:$PATH"' >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCUDA_ARCHITECTURES="86" \
          -DUSE_CCACHE=ON \
          -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.8 \
          -DCMAKE_PREFIX_PATH=/usr/local/cuda-11.8 \
          -DCMAKE_LIBRARY_PATH=/usr/local/cuda-11.8/lib64 \
          -DCUDA_CUBLAS_LIBRARY=/usr/local/cuda-11.8/lib64/libcublas.so \
          -DCUDA_CUSPARSE_LIBRARY=/usr/local/cuda-11.8/lib64/libcusparse.so \
          -DCUDA_CUSOLVER_LIBRARY=/usr/local/cuda-11.8/lib64/libcusolver.so \
          -DCMAKE_VERBOSE_MAKEFILE=ON
    
      - name: Build with CMake
        run: |
          cd build
          make -j$(nproc)
